# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sites', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(max_length=50)),
                ('fb_link', models.CharField(max_length=200, null=True)),
                ('tw_link', models.CharField(max_length=200, null=True)),
                ('insta_link', models.CharField(max_length=200, null=True)),
                ('gplus_link', models.CharField(max_length=200, null=True)),
                ('li_link', models.CharField(max_length=200, null=True)),
                ('member_since', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
